### ISSUE TITLE
Problem Creating new Iteration

### ISSUE THREAD

**Issue by andrtose** [RHEAGROUP/COMET-SDK-Community-Edition#179]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi, I've got a problem on a model, I would like to create a new iteration but both my software and CDP4 gives the same error:

_The ECSS-E-TM-10-25A Annex C Services replied with code NotFound: Not Found: {"message":"Could not find latest iteration."}_

I'm quite sure that the problem is generated by me because I generate a new iteration in the past but without updateing the iteration number, so in this model I have 2 iteration with the same number (1).

The repository is OCDT.

Is there a way to change the iteration number using SDK? Or do you have a suggestion to correct my model?

### System Configuration

- COMET version:
  - [ ] CDP4Common:         
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [X] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
OS WIndows 10 
- .NET Framework version:
4.5
- Additional information:

**Comment by samatrhea** [comment]
The iteration number is determined by the server and cannot be changed using the SDK. The only option you have is to edit the data in the database using a tool like PgAdmin. 

Would be good to know which version of the OCDT WSP you are using, because to me it sounds like you found a bug. A couple of lines from 10-25 Annex A on the `IterationSetup.iterationNumber` property: https://sdk-reference.cdp4.org/#IterationSetup

```
Note: In an implementation the number shall be assigned by the server. The first IterationSetup / Iteration that is created for an EngineeringModelSetup / EngineeringModel shall be 1. Any subsequent IterationSetup / Iteration shall be assigned the next number in the creation sequence. 
```

@alexatrhea can you confirm?

**Comment by alexatrhea** [comment]
Indeed. Fixing in the db would be the only option. It could be indeed possible that the WSP is not processing this properly ans as a workaround OCDT might have been doing it manually, which means that if you use COMET this is not done properly.

It is definitely the cause of the NotFound error as based on the number it cant determine which one of the two is the latest.

**Comment by andrtose** [comment]
Using PgAdmin works! But I have to change also the field "createdOn". I don't' know why the timestamp was the same for the 2 iterations. (the Model is cloned). But with your suggestion it seems the problem is solved. Thank you very much.
