### ISSUE TITLE
Perfomance issue when validating 1 value against +-600 Parametertypes

### ISSUE THREAD

**Issue by nathanatrhea** [RHEAGROUP/COMET-SDK-Community-Edition#186]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

It takes a long time  to validate 1 value against +-600 ParameterTypes when using the value validator.

### System Configuration

- COMET version:
  - [x] CDP4Common:         7.3.0
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by samatrhea** [comment]
@nathanatrhea is this still an issue?

**Comment by nathanatrhea** [comment]
> @nathanatrhea is this still an issue?

In short no, I think I intended to mis-use it.
