### ISSUE TITLE
Computation of the NestedParameter fails if a ValueArray is empty

### ISSUE THREAD

**Issue by antoineatrhea** [RHEAGROUP/COMET-SDK-Community-Edition#308]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

An IndexOutOfRangeException is thrown if on of the ValueArray of the ActualValue is empty. 
This is raised line 687 of the NestedElementTreeGenerator

### System Configuration

- COMET version:
  - [ ] CDP4Common:         
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by samatrhea** [comment]
what is meant with "empty", as in there is no value (either null or string.empty)?

**Comment by antoineatrhea** [comment]
string.empty. Here is a screen shot of a ParameterValueArray that have been queried via http call 
![image](https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/assets/97221392/8b1948a6-7a92-457a-81e1-e62c8d476fa3)

**Comment by samatrhea** [comment]
seems that the data is incorrect, so, we need to make the algorithm robust against this case, but what is the root cause of this?

**Comment by antoineatrhea** [comment]
It seams that the server allowed to update a ParameterValueSet (For a SimpleQuantityKind) with a string.empty value

**Comment by samatrhea** [comment]
> It seams that the server allowed to update a ParameterValueSet (For a SimpleQuantityKind) with a string.empty value

can you create a ticket for the server that we do not allow this?

**Comment by antoineatrhea** [comment]
Sure !
