### ISSUE TITLE
How to Import OCDT Models

### ISSUE THREAD

**Issue by andrtose** [RHEAGROUP/COMET-SDK-Community-Edition#95]
Dear All,

I want to load a OCDT Model  by using  WSP and store to CDP4.
Is there any feature or example to do this or I've to write my own code?

Kind regards,
Andrea

**Comment by alexatrhea** [comment]
Hi, can you explain a bit clearer what do you want to do? Do you want to transfer a model from wsp to cdp server? Or do you want to just work on a model that is on WSP using cdp4 IME? If the latter, you can just connect to a WSP when logging on just select OCDT WSP as the source type. If it is the former, there is currently no easy way to do this.

**Comment by andrtose** [comment]
Hi Alex,
The hardest one is the way!! :-)
So, to trasfer data from WSP to CDP I've to write my own procedure, could you help me my initial proposal is:

1. Create Engineering Model
2. Create One Iteration. (I'll copy only the last one
3. Create Model RDL.
4. Copy Categories, Parameter Type and other items in original model RDL.
5. Copy Options and States
6. Copy Element Definition and Usages.

It is correct this approach?

Kind regards,
Andrea

**Comment by samatrhea** [comment]
@andrtose and @alexatrhea I propose we create a new GitHub repos that contains a project to do exactly that, use low level SQL to migrate all data between a WSP Server and a CDP4 Server. We can collaborate on this and it may be a feature we will need in the future anyway

**Comment by andrtose** [comment]
@samatrhea and @alexatrhea I think it is a good solution to migrate all the database! Also working at low level is good because we are using an old version of OCDT (WSP 1.0.1).

**Comment by samatrhea** [comment]
@andrtose I think this issue will be resolved in collaboration with ESA in April. I propose that you wait for a couple of weeks and lets see whether we can all contribute to making it possible to migrate the OCDT database to a CDP4 database

**Comment by andrtose** [comment]
Very good! I'll wait for your news.

**Comment by samatrhea** [comment]
@alexatrhea can you provide an update on the status of this issue to @andrtose.

**Comment by andrtose** [comment]
Hi, do you have any news about this topic?

**Comment by alexatrhea** [comment]
@andrtose have you seen the new SAT tool? https://github.com/RHEAGROUP/COMET-Server-Administration-Tool

it has some functionality to migrate an OCDT server to a COMET server. https://github.com/RHEAGROUP/COMET-Server-Administration-Tool/wiki/Server-Migration describe the process. Keep in mind that the target COMET server must be fresh and not contain any data that you are not afraid to lose.
